# Generated by Django 2.2.13 on 2025-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
