# Generated by Django 2.2.13 on 2025-11-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicom', '0002_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('ai', 'AI Agent')], max_length=5),
        ),
    ]
